name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
<<<<<<< HEAD
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@bb0ed26fdd3c1bbfbca6f384a01a304fab954a00"
=======
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@b86383fb28a160eeaf3e13cbf99469a0ed4cfcb2"
>>>>>>> f8714703a9f6681e0722d3bd954bc5db32f019f0
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "config.py"
      siteurl: "https://kevinisageek.github.io"
      requirements: "pelican[markdown] bs4"
